version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start:dev
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservices
    ports:
      - "5432:5432"

